version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-cpu
      args:
        env: local
    command: python3.8 run.py
    volumes:
      - .:/image-caption-generator